name: Notificaci贸n al subir c贸digo

on:
  push:  # Se ejecuta cuando alguien hace push al repositorio
    branches:
      - main  # Puedes cambiarlo por otra rama si quieres

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar notificaci贸n a ntfy.sh
        run: |
          curl -H "Title:  Nuevo push en el repositorio" \
               -H "Priority: 3" \
               -d "Se ha subido nuevo c贸digo al repositorio en la rama ${{ github.ref_name }} por ${{ github.actor }}" \
               https://ntfy.sh/devops-itla